/**
 * exportBlockManager.js — Managed export block utilities.
 *
 * Detects, creates, appends to, and removes from managed `export { }` blocks
 * at the bottom of JS/TS files. Pure JS — no Monaco or editor dependencies.
 *
 * A "managed block" is the LAST `export { ... }` statement in a file that
 * is NOT a re-export (no `from` clause). It is the single aggregation point
 * for exports generated by the node system.
 *
 * Exported API:
 *   findManagedExportBlock(text)                     → BlockInfo | null
 *   findInlineExport(text, symbolName)               → number | -1
 *   addToExportBlock(text, filePath, symbolName)      → PatchPlan[]
 *   removeFromExportBlock(text, filePath, symbolName) → PatchPlan[]
 */

// ---------------------------------------------------------------------------
// findManagedExportBlock
// ---------------------------------------------------------------------------

/**
 * Find the managed export block in file text, if present.
 * Looks for the LAST `export { ... }` block that is NOT a re-export (no `from`).
 *
 * @param {string} text - Full source file content.
 * @returns {{ startLine: number, endLine: number, symbols: string[] } | null}
 *   Lines are 0-indexed. `symbols` are the names inside the block.
 */
export function findManagedExportBlock(text) {
  const lines = text.split('\n');
  let lastBlock = null;

  let i = 0;
  while (i < lines.length) {
    const trimmed = lines[i].trimStart();

    // Match `export {` or `export type {` at start of line (skip re-exports below)
    if (/^export\s+(?:type\s+)?\{/.test(trimmed)) {
      const startLine = i;
      let blockLines = [lines[i]];
      let j = i;

      // Collect lines until we find the closing `}`
      while (j < lines.length && !blockLines.join('').includes('}')) {
        j++;
        if (j < lines.length) blockLines.push(lines[j]);
      }

      const block = blockLines.join(' ');
      const endLine = j < lines.length ? j : lines.length - 1;

      // Skip re-exports: `export { X } from '...'`
      if (/\}\s*from\s*['"`]/.test(block)) {
        i = endLine + 1;
        continue;
      }

      // Extract symbol names from the block
      const inner = block.replace(/^[^{]*\{/, '').replace(/\}.*$/, '');
      const symbols = _parseBlockSymbols(inner);

      lastBlock = { startLine, endLine, symbols };
      i = endLine + 1;
      continue;
    }

    i++;
  }

  return lastBlock;
}

// ---------------------------------------------------------------------------
// findInlineExport
// ---------------------------------------------------------------------------

/**
 * Check if a symbol is already exported inline (e.g., `export const X`,
 * `export function X`, `export class X`, `export default function X`).
 *
 * @param {string} text       - Full source file content.
 * @param {string} symbolName - Name to search for.
 * @returns {number} 0-indexed line number where the inline export is, or -1.
 */
export function findInlineExport(text, symbolName) {
  const lines = text.split('\n');
  const escaped = symbolName.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const patterns = [
    new RegExp(`^export\\s+(?:async\\s+)?function\\s+${escaped}\\b`),
    new RegExp(`^export\\s+(?:abstract\\s+)?class\\s+${escaped}\\b`),
    new RegExp(`^export\\s+(?:const|let|var)\\s+${escaped}\\b`),
    new RegExp(`^export\\s+type\\s+${escaped}\\s*[=<]`),
    new RegExp(`^export\\s+(?:abstract\\s+)?(?:interface|enum)\\s+${escaped}\\b`),
    new RegExp(`^export\\s+default\\s+(?:async\\s+)?(?:function|class)\\s+${escaped}\\b`),
  ];

  for (let i = 0; i < lines.length; i++) {
    const trimmed = lines[i].trimStart();
    for (const re of patterns) {
      if (re.test(trimmed)) return i;
    }
  }

  return -1;
}

// ---------------------------------------------------------------------------
// addToExportBlock
// ---------------------------------------------------------------------------

/**
 * Generate patch plans to add a symbol to the managed export block.
 *
 * Rules:
 *  - If the symbol is already inline-exported, returns empty array (no-op).
 *  - If a managed block exists, rewrites it to include the new symbol.
 *  - If no managed block exists, creates `export { symbolName };` at EOF.
 *
 * @param {string} text       - Full source file content.
 * @param {string} filePath   - Absolute file path (for patch plan filePath field).
 * @param {string} symbolName - Name to add to the export block.
 * @returns {Array<{kind: string, filePath: string, [key: string]: any}>}
 */
export function addToExportBlock(text, filePath, symbolName) {
  // No-op if already inline-exported
  if (findInlineExport(text, symbolName) >= 0) return [];

  const existing = findManagedExportBlock(text);

  if (existing) {
    // Already in the block? No-op.
    if (existing.symbols.includes(symbolName)) return [];

    // Rewrite the block with the new symbol appended
    const newSymbols = [...existing.symbols, symbolName];
    const newBlockText = `export { ${newSymbols.join(', ')} };\n`;

    if (existing.startLine === existing.endLine) {
      // Single-line block — replace that line
      return [{
        kind: 'replace',
        filePath,
        line: existing.startLine,
        text: newBlockText,
      }];
    }

    // Multi-line block — remove all lines, insert replacement at startLine
    const plans = [];
    // Remove lines from endLine down to startLine+1 (bottom-first)
    for (let ln = existing.endLine; ln > existing.startLine; ln--) {
      plans.push({ kind: 'removeLine', filePath, line: ln });
    }
    // Replace the startLine with the new single-line block
    plans.push({ kind: 'replace', filePath, line: existing.startLine, text: newBlockText });
    return plans;
  }

  // No existing managed block — create one at EOF
  const lineCount = text.split('\n').length;
  const endsWithNewline = text.endsWith('\n');
  const prefix = endsWithNewline ? '' : '\n';

  return [{
    kind: 'insert',
    filePath,
    insertLine: lineCount,
    text: `${prefix}export { ${symbolName} };\n`,
  }];
}

// ---------------------------------------------------------------------------
// removeFromExportBlock
// ---------------------------------------------------------------------------

/**
 * Generate patch plans to remove a symbol from the managed export block.
 *
 * Rules:
 *  - Only affects the managed export block. Never touches inline exports.
 *  - If the block becomes empty after removal, removes the entire block.
 *
 * @param {string} text       - Full source file content.
 * @param {string} filePath   - Absolute file path.
 * @param {string} symbolName - Name to remove from the block.
 * @returns {Array<{kind: string, filePath: string, [key: string]: any}>}
 */
export function removeFromExportBlock(text, filePath, symbolName) {
  const existing = findManagedExportBlock(text);
  if (!existing) return [];

  // Symbol not in block? No-op.
  if (!existing.symbols.includes(symbolName)) return [];

  const remaining = existing.symbols.filter((s) => s !== symbolName);

  if (remaining.length === 0) {
    // Block is now empty — remove all block lines (bottom-first)
    const plans = [];
    for (let ln = existing.endLine; ln >= existing.startLine; ln--) {
      plans.push({ kind: 'removeLine', filePath, line: ln });
    }
    return plans;
  }

  // Rewrite the block without the removed symbol
  const newBlockText = `export { ${remaining.join(', ')} };\n`;

  if (existing.startLine === existing.endLine) {
    return [{ kind: 'replace', filePath, line: existing.startLine, text: newBlockText }];
  }

  // Multi-line → collapse to single-line
  const plans = [];
  for (let ln = existing.endLine; ln > existing.startLine; ln--) {
    plans.push({ kind: 'removeLine', filePath, line: ln });
  }
  plans.push({ kind: 'replace', filePath, line: existing.startLine, text: newBlockText });
  return plans;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Parse symbol names from the inner content of an export block.
 * Handles: `Name`, `Name as Alias` (returns Alias), whitespace/newlines.
 *
 * @param {string} inner - Content between `{` and `}`.
 * @returns {string[]}
 */
function _parseBlockSymbols(inner) {
  const results = [];
  const entries = inner.split(',');
  for (const entry of entries) {
    const trimmed = entry.trim();
    if (!trimmed) continue;

    // "Name as Alias" → keep Alias
    const asMatch = trimmed.match(/^[A-Za-z_$][A-Za-z0-9_$]*\s+as\s+([A-Za-z_$][A-Za-z0-9_$]*)$/);
    if (asMatch) {
      results.push(asMatch[1]);
      continue;
    }

    // Plain "Name"
    if (/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(trimmed)) {
      results.push(trimmed);
    }
  }
  return results;
}
