const PLATFORM_DEFAULTS = {
  macos: {
    os: 'macos',
    modifierKey: '\u2318',
    modifierKeyCode: 'Meta',
    altKeyLabel: '\u2325',
    placeholderPath: '~/Projects/my-project',
    projectsDirName: 'Projects',
    hiddenFiles: ['.DS_Store', '._*', '.Spotlight-V100', '.Trashes'],
    showWindowControls: false,
    shortcutLabels: {
      save: '\u2318S',
      saveAll: '\u21e7\u2318S',
      undo: '\u2318Z',
      redo: '\u21e7\u2318Z',
      find: '\u2318F',
      split: '\u2318\\',
      fitContent: '\u23180',
      fitSelection: '\u21e7\u23180',
      findNode: '\u2318P',
      selectAll: '\u2318A',
      editMode: 'E',
      hudToggle: 'H',
    },
  },

  windows: {
    os: 'windows',
    modifierKey: 'Ctrl',
    modifierKeyCode: 'Control',
    altKeyLabel: 'Alt',
    placeholderPath: 'C:\\Projects\\my-project',
    projectsDirName: 'Projects',
    hiddenFiles: ['Thumbs.db', 'desktop.ini'],
    showWindowControls: true,
    shortcutLabels: {
      save: 'Ctrl+S',
      saveAll: 'Ctrl+Shift+S',
      undo: 'Ctrl+Z',
      redo: 'Ctrl+Y',
      find: 'Ctrl+F',
      split: 'Ctrl+\\',
      fitContent: 'Ctrl+0',
      fitSelection: 'Ctrl+Shift+0',
      findNode: 'Ctrl+P',
      selectAll: 'Ctrl+A',
      editMode: 'E',
      hudToggle: 'H',
    },
  },

  linux: {
    os: 'linux',
    modifierKey: 'Ctrl',
    modifierKeyCode: 'Control',
    altKeyLabel: 'Alt',
    placeholderPath: '~/projects/my-project',
    projectsDirName: 'Projects',
    hiddenFiles: ['.directory'],
    showWindowControls: true,
    shortcutLabels: {
      save: 'Ctrl+S',
      saveAll: 'Ctrl+Shift+S',
      undo: 'Ctrl+Z',
      redo: 'Ctrl+Shift+Z',
      find: 'Ctrl+F',
      split: 'Ctrl+\\',
      fitContent: 'Ctrl+0',
      fitSelection: 'Ctrl+Shift+0',
      findNode: 'Ctrl+P',
      selectAll: 'Ctrl+A',
      editMode: 'E',
      hudToggle: 'H',
    },
  },
};

export default PLATFORM_DEFAULTS;

